name: bootcamp_laura
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  lorem_gen: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  chat_bubbles: ^1.6.0


flutter:
  fonts:
    - family: Lato
      fonts:
      - asset: fonts/Lato-Bold.ttf
  uses-material-design: true
  assets:
  - assets/login.png
  - assets/facebook_logo.png
  - assets/google_logo.png
  - assets/twitter_logo.png
  - assets/cesta.jpeg
  - assets/perfil.png
  - assets/json/model.json

